const routes = {
  LANDING_PAGE: 'https://getdaabo.com.ng',
  LOGIN: '/login',
  PROFILE: '/account-settings?tab=personal',
  HELP_SUPPORT: 'https://intercom.help/daabo/en',
  LOGIN_ACTIVITY: '/account-settings?tab=settings',
  SPREAD: 'https://getdaabo.com.ng',
  ABOUT: 'https://www.getdaabo.com.ng/about/company',
  PRIVACY_POLICY: 'https://www.getdaabo.com.ng/privacy-policy',
  TERMS_OF_SERVICE: 'https://www.getdaabo.com.ng/terms-of-service',
  DASHBOARD: '/',
  DEVICES: '/devices',
  BILLING: '/billing',
  MAPS_ACTIONS: '/maps-actions',
  CLAIMS_REPAIRS: '/claims-repairs',
  ACCOUNT_SETTINGS: '/account-settings',
  RESET_PASSWORD: '/reset_password',
  RESET_PASSWORD_VERIFICATION: '/reset_password_verifiaction',
  RESET_PASSWORD_SUCCESSFUL: '/reset_password_successful',
  EMAIL_SENT: '/email_sent',
  EMAIL_VERIFICATION_NOTIFICATION: '/email_verification_notification',
  CREATE_PASSWORD: '/create_password',
} as const;

export default routes;
